### ISSUE TITLE
Unknown host error when modify runnodes command

### ISSUE THREAD

**Issue by vivekshah92** [180Protocol/180protocol#12]
Unknown host error when modify runnodes command like below

if [ -z "$JAVA_HOME" ] && which osascript >/dev/null; then /usr/libexec/java_home --exec java -jar corda.jar run-migration-scripts --core-schemas "$@" /usr/libexec/java_home --exec java -jar corda.jar --allow-hibernate-to-manage-app-schema "$@" else "${JAVA_HOME:+$JAVA_HOME/bin/}java" -jar corda.jar run-migration-scripts --core-schemas "$@" "${JAVA_HOME:+$JAVA_HOME/bin/}java" -jar corda.jar --allow-hibernate-to-manage-app-schema "$@" fi

**Comment by parthbond180** [comment]
updating README with correctly formatted instruction
