### ISSUE TITLE
Enclave service is instantiated at node startup on Host and can cause data leaks across two consumer aggregation requests

### ISSUE THREAD

**Issue by shukpa** [180Protocol/180protocol#16]
**Describe the bug**
Enclave service is instantiated at node startup on Host and can cause data leaks across two consumer aggregation requests

**To Reproduce**
1. Instantiate network using docker compose
2. Start consumer aggregation request from consumer node
3. Start another consumer aggregation request from consumer node
4. Data outputs from the previous request show up in the second output

**Expected behavior**
Only current output should be shown. Enclave service lifecycle should be request dependent not shared across host node's entire lifecycle. 

- Check Corda API to assess if CordaService lifecycle can be controlled within the consumer aggregation flow

**Comment by hiteshvpatel256** [comment]
No option found from corda docs & api to manage corda service after node deployment. 

It's required to launch corda service in prototype mode for every aggregation cycle. 

Completable future seems to be an another option to achieve our use case scenario. Doing research on this right now.

Also trying out launching multiple aggregation cycle to find out the way resources shared between multiple flow from single service.
